version: '3.8'

services:
  app:
    image: patientor-frontend
    build:
      context: ./patientor-frontend
      dockerfile: Dockerfile
    container_name: patientor-app-prod
    restart: always
    depends_on:
      - server

  server:
    image: patientor-backend
    build:
      context: ./patientor-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=${REDIS_URL}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    container_name: patientor-server-prod
    restart: always
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4.18
    ports:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./patientor-backend/src/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./patientor-backend/mongo_data:/data/db

  redis:
    image: redis
    ports:
      - 6379
    command: redis-server --requirepass ${REDIS_PASSWORD}

  nginx:
    image: nginxinc/nginx-unprivileged:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    container_name: reverse-proxy
    restart: always
    depends_on:
      - app
      - server
