version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./src/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  debug-helper:
    image: busybox
